project_id: 407378
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true

files:
  - source: /manual/nitrofiles/languages/en/*
    translation: /manual/nitrofiles/languages/%two_letters_code%/%original_file_name%
  - source: /quickmenu/nitrofiles/languages/en/*
    translation: /quickmenu/nitrofiles/languages/%two_letters_code%/%original_file_name%
  - source: /romsel_dsimenutheme/nitrofiles/languages/en/*
    translation: /romsel_dsimenutheme/nitrofiles/languages/%two_letters_code%/%original_file_name%
  - source: /settings/nitrofiles/languages/en/*
    translation: /settings/nitrofiles/languages/%two_letters_code%/%original_file_name%
  - source: /title/nitrofiles/languages/en/*
    translation: /title/nitrofiles/languages/%two_letters_code%/%original_file_name%
