#---------------------------------------------------------------------------------
# PACKAGE is the directory where final published files will be placed
#---------------------------------------------------------------------------------
PACKAGE		:=	../7zfile

#---------------------------------------------------------------------------------
# Goals for Build
#---------------------------------------------------------------------------------
.PHONY:

all:	$(PACKAGE)/_nds/TWiLightMenu/extras/apfix.pck

$(PACKAGE)/_nds/TWiLightMenu/extras/apfix.pck:
	./pack_apfix.py
