#ifndef DEFAULT_SETTINGS_H
#define DEFAULT_SETTINGS_H

#define DEFAULT_PHAT_COLORS false
#define DEFAULT_BOOST_CPU false
#define DEFAULT_BOOST_VRAM false
#define DEFAULT_DSI_MODE 1
#define DEFAULT_CARD_READ_DMA true
#define DEFAULT_ASYNC_CARD_READ false
#define DEFAULT_SWI_HALT_HOOK false

#endif // DEFAULT_SETTINGS_H
