/*======================================================================

   font_16x16 texture coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef FONT_16X16__H
#define FONT_16X16__H


#define FONT_16X16_BITMAP_WIDTH   64
#define FONT_16X16_BITMAP_HEIGHT  512
#define FONT_16X16_NUM_IMAGES   96

#define CAPS_SX 14
#define LOWER_SX 9
#define TEXT_SY 16
		//	Format:
		//	U,V,Width,Height



extern const unsigned int font_16x16_texcoords[] = {
	0, 0, 8, TEXT_SY, // Space
	16, 0, CAPS_SX, TEXT_SY, // 1
	32, 0, CAPS_SX, TEXT_SY, // 2
	48, 0, CAPS_SX, TEXT_SY, // 3
	0, 16, CAPS_SX, TEXT_SY, // 4
	16, 16, CAPS_SX, TEXT_SY, // 5
	32, 16, CAPS_SX, TEXT_SY, // 6
	48, 16, CAPS_SX, TEXT_SY, // 7
	0, 32, CAPS_SX, TEXT_SY, // 8
	16, 32, CAPS_SX, TEXT_SY, // 9
	32, 32, CAPS_SX, TEXT_SY, // 10
	48, 32, CAPS_SX, TEXT_SY, // 11
	0, 48, CAPS_SX, TEXT_SY, // 12
	16, 48, CAPS_SX, TEXT_SY, // 13
	32, 48, CAPS_SX, TEXT_SY, // 14
	48, 48, 12, TEXT_SY, // /
	0, 64, CAPS_SX, TEXT_SY, // 16
	16, 64, CAPS_SX, TEXT_SY, // 17
	32, 64, CAPS_SX, TEXT_SY, // 18
	48, 64, CAPS_SX, TEXT_SY, // 19
	0, 80, CAPS_SX, TEXT_SY, // 20
	16, 80, CAPS_SX, TEXT_SY, // 21
	32, 80, CAPS_SX, TEXT_SY, // 22
	48, 80, CAPS_SX, TEXT_SY, // 23
	0, 96, CAPS_SX, TEXT_SY, // 24
	16, 96, CAPS_SX, TEXT_SY, // 25
	32, 96, 8, TEXT_SY, // :
	48, 96, 8, TEXT_SY, // ;
	0, 112, CAPS_SX, TEXT_SY, // 28
	16, 112, CAPS_SX, TEXT_SY, // 29
	32, 112, CAPS_SX, TEXT_SY, // 30
	48, 112, CAPS_SX, TEXT_SY, // 31
	0, 128, CAPS_SX, TEXT_SY, // 32
	16, 128, CAPS_SX, TEXT_SY, // 33
	32, 128, CAPS_SX, TEXT_SY, // 34
	48, 128, CAPS_SX, TEXT_SY, // 35
	0, 144, CAPS_SX, TEXT_SY, // 36
	16, 144, CAPS_SX, TEXT_SY, // 37
	32, 144, CAPS_SX, TEXT_SY, // 38
	48, 144, CAPS_SX, TEXT_SY, // 39
	0, 160, CAPS_SX, TEXT_SY, // 40
	16, 160, CAPS_SX, TEXT_SY, // 41
	32, 160, CAPS_SX, TEXT_SY, // 42
	48, 160, CAPS_SX, TEXT_SY, // 43
	0, 176, CAPS_SX, TEXT_SY, // 44
	16, 176, CAPS_SX, TEXT_SY, // 45
	32, 176, CAPS_SX, TEXT_SY, // 46
	48, 176, CAPS_SX, TEXT_SY, // 47
	0, 192, CAPS_SX, TEXT_SY, // 48
	16, 192, CAPS_SX, TEXT_SY, // 49
	32, 192, CAPS_SX, TEXT_SY, // 50
	48, 192, CAPS_SX, TEXT_SY, // 51
	0, 208, CAPS_SX, TEXT_SY, // 52
	16, 208, CAPS_SX, TEXT_SY, // 53
	32, 208, CAPS_SX, TEXT_SY, // 54
	48, 208, CAPS_SX, TEXT_SY, // 55
	0, 224, CAPS_SX, TEXT_SY, // 56
	16, 224, CAPS_SX, TEXT_SY, // 57
	32, 224, CAPS_SX, TEXT_SY, // 58
	48, 224, CAPS_SX, TEXT_SY, // 59
	0, 240, CAPS_SX, TEXT_SY, // 60
	16, 240, CAPS_SX, TEXT_SY, // 61
	32, 240, CAPS_SX, TEXT_SY, // 62
	48, 240, CAPS_SX, TEXT_SY, // 63
	0, 256, CAPS_SX, TEXT_SY, // 64
	16, 256, 7, TEXT_SY, // a
	32, 256, 8, TEXT_SY, // b
	48, 256, 7, TEXT_SY, // c
	0, 272, 8, TEXT_SY, // d
	16, 272, 8, TEXT_SY, // e
	32, 272, 6, TEXT_SY, // f
	48, 272, 9, TEXT_SY, // g
	0, 288, 7, TEXT_SY, // h
	16, 288, 3, TEXT_SY, // i
	32, 288, 4, TEXT_SY, // j
	48, 288, 7, TEXT_SY, // k
	0, 304, 3, TEXT_SY, // l
	16, 304, 9, TEXT_SY, // m
	32, 304, 7, TEXT_SY, // n
	48, 304, 9, TEXT_SY, // o
	0, 320, 8, TEXT_SY, // p
	16, 320, 8, TEXT_SY, // q
	32, 320, 6, TEXT_SY, // r
	48, 320, 7, TEXT_SY, // s
	0, 336, 6, TEXT_SY, // t
	16, 336, 7, TEXT_SY, // u
	32, 336, 6, TEXT_SY, // v
	48, 336, 9, TEXT_SY, // w
	0, 352, 7, TEXT_SY, // x
	16, 352, 7, TEXT_SY, // y
	32, 352, 6, TEXT_SY, // z
	48, 352, CAPS_SX, TEXT_SY, // 91
	0, 368, CAPS_SX, TEXT_SY, // 92
	16, 368, CAPS_SX, TEXT_SY, // 93
	32, 368, CAPS_SX, TEXT_SY, // 94
	48, 368, CAPS_SX, TEXT_SY, // 95
};


#endif
