#include <nds.h>
#include <stdio.h>
#include <fat.h>
#include <sys/stat.h>
#include <string.h>
#include <unistd.h>

#include "inifile.h"
#include "nitrofs.h"

// Strings
std::string STR_SAVING_SETTINGS = "STR_SAVING_SETTINGS";
std::string STR_SETTINGS_SAVED = "STR_SETTINGS_SAVED";

std::string STR_LR_SWITCH = "STR_LR_SWITCH";
std::string STR_GUI_SETTINGS = "STR_GUI_SETTINGS";
std::string STR_GAMESAPPS_SETTINGS = "STR_GAMESAPPS_SETTINGS";

// GUI settings
std::string STR_THEME = "STR_THEME";
std::string STR_LASTPLAYEDROM = "STR_LASTPLAYEDROM";
std::string STR_DSIMENUPPLOGO = "STR_DSIMENUPPLOGO";
std::string STR_DIRECTORIES = "STR_DIRECTORIES";
std::string STR_BOXART = "STR_BOXART";
std::string STR_ANIMATEDSIICONS = "STR_ANIMATEDSIICONS";
std::string STR_REPLACEDSIMENU = "STR_REPLACEDSIMENU";
std::string STR_RESTOREDSIMENU = "STR_RESTOREDSIMENU";

std::string STR_SHOW = "STR_SHOW";
std::string STR_HIDE = "STR_HIDE";

std::string STR_DESCRIPTION_THEME_1 = "STR_DESCRIPTION_THEME_1";
std::string STR_DESCRIPTION_THEME_2 = "STR_DESCRIPTION_THEME_2";

std::string STR_DESCRIPTION_LASTPLAYEDROM_1 = "STR_DESCRIPTION_LASTPLAYEDROM_1";
std::string STR_DESCRIPTION_LASTPLAYEDROM_2 = "STR_DESCRIPTION_LASTPLAYEDROM_2";
std::string STR_DESCRIPTION_LASTPLAYEDROM_3 = "STR_DESCRIPTION_LASTPLAYEDROM_3";
std::string STR_DESCRIPTION_LASTPLAYEDROM_4 = "STR_DESCRIPTION_LASTPLAYEDROM_4";

std::string STR_DESCRIPTION_DSIMENUPPLOGO_1 = "STR_DESCRIPTION_DSIMENUPPLOGO_1";
std::string STR_DESCRIPTION_DSIMENUPPLOGO_2 = "STR_DESCRIPTION_DSIMENUPPLOGO_2";
std::string STR_DESCRIPTION_DSIMENUPPLOGO_3 = "STR_DESCRIPTION_DSIMENUPPLOGO_3";

std::string STR_DESCRIPTION_DIRECTORIES_1 = "STR_DESCRIPTION_DIRECTORIES_1";
std::string STR_DESCRIPTION_DIRECTORIES_2 = "STR_DESCRIPTION_DIRECTORIES_2";
std::string STR_DESCRIPTION_DIRECTORIES_3 = "STR_DESCRIPTION_DIRECTORIES_3";

std::string STR_DESCRIPTION_BOXART_1 = "STR_DESCRIPTION_BOXART_1";
std::string STR_DESCRIPTION_BOXART_2 = "STR_DESCRIPTION_BOXART_2";

std::string STR_DESCRIPTION_ANIMATEDSIICONS_1 = "STR_DESCRIPTION_ANIMATEDSIICONS_1";
std::string STR_DESCRIPTION_ANIMATEDSIICONS_2 = "STR_DESCRIPTION_ANIMATEDSIICONS_2";
std::string STR_DESCRIPTION_ANIMATEDSIICONS_3 = "STR_DESCRIPTION_ANIMATEDSIICONS_3";

std::string STR_DESCRIPTION_REPLACEDSIMENU_1 = "STR_DESCRIPTION_REPLACEDSIMENU_1";
std::string STR_DESCRIPTION_REPLACEDSIMENU_2 = "STR_DESCRIPTION_REPLACEDSIMENU_2";

std::string STR_DESCRIPTION_RESTOREDSIMENU_1 = "STR_DESCRIPTION_RESTOREDSIMENU_1";

// Games/Apps settings
std::string STR_LANGUAGE = "STR_LANGUAGE";
std::string STR_CPUSPEED = "STR_CPUSPEED";
std::string STR_DEBUG = "STR_DEBUG";
std::string STR_ROMREADLED = "STR_ROMREADLED";
std::string STR_SNDFREQ = "STR_SNDFREQ";
std::string STR_RESETSLOT1 = "STR_RESETSLOT1";
std::string STR_LOADINGSCREEN = "STR_LOADINGSCREEN";
std::string STR_BOOTSTRAP = "STR_BOOTSTRAP";
std::string STR_USEGBARUNNER2 = "STR_USEGBARUNNER2";

std::string STR_SYSTEM = "STR_SYSTEM";
std::string STR_ON = "STR_ON";
std::string STR_OFF = "STR_OFF";
std::string STR_YES = "STR_YES";
std::string STR_NO = "STR_NO";
std::string STR_NONE = "STR_NONE";
std::string STR_POWER = "STR_POWER";
std::string STR_CAMERA = "STR_CAMERA";
std::string STR_REGULAR = "STR_REGULAR";
std::string STR_RELEASE = "STR_RELEASE";
std::string STR_NIGHTLY = "STR_NIGHTLY";

std::string STR_DESCRIPTION_LANGUAGE_1 = "STR_DESCRIPTION_LANGUAGE_1";
std::string STR_DESCRIPTION_LANGUAGE_2 = "STR_DESCRIPTION_LANGUAGE_2";
std::string STR_DESCRIPTION_LANGUAGE_3 = "STR_DESCRIPTION_LANGUAGE_3";

std::string STR_DESCRIPTION_CPUSPEED_1 = "STR_DESCRIPTION_CPUSPEED_1";
std::string STR_DESCRIPTION_CPUSPEED_2 = "STR_DESCRIPTION_CPUSPEED_2";

std::string STR_DESCRIPTION_DEBUG_1 = "STR_DESCRIPTION_DEBUG_1";
std::string STR_DESCRIPTION_DEBUG_2 = "STR_DESCRIPTION_DEBUG_2";

std::string STR_DESCRIPTION_ROMREADLED_1 = "STR_DESCRIPTION_ROMREADLED_1";

std::string STR_DESCRIPTION_SNDFREQ_1 = "STR_DESCRIPTION_SNDFREQ_1";
std::string STR_DESCRIPTION_SNDFREQ_2 = "STR_DESCRIPTION_SNDFREQ_2";

std::string STR_DESCRIPTION_RESETSLOT1_1 = "STR_DESCRIPTION_RESETSLOT1_1";
std::string STR_DESCRIPTION_RESETSLOT1_2 = "STR_DESCRIPTION_RESETSLOT1_2";

std::string STR_DESCRIPTION_LOADINGSCREEN_1 = "STR_DESCRIPTION_LOADINGSCREEN_1";
std::string STR_DESCRIPTION_LOADINGSCREEN_2 = "STR_DESCRIPTION_LOADINGSCREEN_2";

std::string STR_DESCRIPTION_BOOTSTRAP_1 = "STR_DESCRIPTION_BOOTSTRAP_1";
std::string STR_DESCRIPTION_BOOTSTRAP_2 = "STR_DESCRIPTION_BOOTSTRAP_2";

std::string STR_DESCRIPTION_FLASHCARD_1 = "STR_DESCRIPTION_FLASHCARD_1";
std::string STR_DESCRIPTION_FLASHCARD_2 = "STR_DESCRIPTION_FLASHCARD_2";

std::string STR_DESCRIPTION_GBARUNNER2_1 = "STR_DESCRIPTION_GBARUNNER2_1";
std::string STR_DESCRIPTION_GBARUNNER2_2 = "STR_DESCRIPTION_GBARUNNER2_2";

// Flashcard settings
std::string STR_FLASHCARD_SELECT = "STR_FLASHCARD_SELECT";
std::string STR_LEFTRIGHT_FLASHCARD = "STR_LEFTRIGHT_FLASHCARD";
std::string STR_AB_SETRETURN = "STR_AB_SETRETURN";


/**
 * Initialize translations.
 * Uses the language ID specified in settings.ui.language.
 */
void langInit(void)
{
	if (nitroFSInit("/_nds/dsimenuplusplus/main.srldr")) {	// Init Nitro FS
		CIniFile languageini( "nitro:/languages/english.ini" );

		STR_SAVING_SETTINGS = languageini.GetString("LANGUAGE", "SAVING_SETTINGS", "");
		STR_SETTINGS_SAVED = languageini.GetString("LANGUAGE", "SETTINGS_SAVED", "");

		STR_LR_SWITCH = languageini.GetString("LANGUAGE", "LR_SWITCH", "");
		STR_GUI_SETTINGS = languageini.GetString("LANGUAGE", "GUI_SETTINGS", "");
		STR_GAMESAPPS_SETTINGS = languageini.GetString("LANGUAGE", "GAMESAPPS_SETTINGS", "");

		// GUI settings
		STR_THEME = languageini.GetString("LANGUAGE", "THEME", "");
		STR_LASTPLAYEDROM = languageini.GetString("LANGUAGE", "LASTPLAYEDROM", "");
		STR_DSIMENUPPLOGO = languageini.GetString("LANGUAGE", "DSIMENUPPLOGO", "");
		STR_DIRECTORIES = languageini.GetString("LANGUAGE", "DIRECTORIES", "");
		STR_BOXART = languageini.GetString("LANGUAGE", "BOXART", "");
		STR_ANIMATEDSIICONS = languageini.GetString("LANGUAGE", "ANIMATEDSIICONS", "");
		STR_REPLACEDSIMENU = languageini.GetString("LANGUAGE", "REPLACEDSIMENU", "");
		STR_RESTOREDSIMENU = languageini.GetString("LANGUAGE", "RESTOREDSIMENU", "");

		STR_SHOW = languageini.GetString("LANGUAGE", "SHOW", "");
		STR_HIDE = languageini.GetString("LANGUAGE", "HIDE", "");

		STR_DESCRIPTION_THEME_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_THEME_1", "");
		STR_DESCRIPTION_THEME_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_THEME_2", "");

		STR_DESCRIPTION_LASTPLAYEDROM_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_LASTPLAYEDROM_1", "");
		STR_DESCRIPTION_LASTPLAYEDROM_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_LASTPLAYEDROM_2", "");
		STR_DESCRIPTION_LASTPLAYEDROM_3 = languageini.GetString("LANGUAGE", "DESCRIPTION_LASTPLAYEDROM_3", "");
		STR_DESCRIPTION_LASTPLAYEDROM_4 = languageini.GetString("LANGUAGE", "DESCRIPTION_LASTPLAYEDROM_4", "");

		STR_DESCRIPTION_DSIMENUPPLOGO_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_DSIMENUPPLOGO_1", "");
		STR_DESCRIPTION_DSIMENUPPLOGO_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_DSIMENUPPLOGO_2", "");
		STR_DESCRIPTION_DSIMENUPPLOGO_3 = languageini.GetString("LANGUAGE", "DESCRIPTION_DSIMENUPPLOGO_3", "");

		STR_DESCRIPTION_DIRECTORIES_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_DIRECTORIES_1", "");
		STR_DESCRIPTION_DIRECTORIES_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_DIRECTORIES_2", "");
		STR_DESCRIPTION_DIRECTORIES_3 = languageini.GetString("LANGUAGE", "DESCRIPTION_DIRECTORIES_3", "");

		STR_DESCRIPTION_BOXART_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_BOXART_1", "");
		STR_DESCRIPTION_BOXART_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_BOXART_2", "");

		STR_DESCRIPTION_ANIMATEDSIICONS_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_ANIMATEDSIICONS_1", "");
		STR_DESCRIPTION_ANIMATEDSIICONS_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_ANIMATEDSIICONS_2", "");
		STR_DESCRIPTION_ANIMATEDSIICONS_3 = languageini.GetString("LANGUAGE", "DESCRIPTION_ANIMATEDSIICONS_3", "");

		STR_DESCRIPTION_REPLACEDSIMENU_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_REPLACEDSIMENU_1", "");
		STR_DESCRIPTION_REPLACEDSIMENU_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_REPLACEDSIMENU_2", "");

		STR_DESCRIPTION_RESTOREDSIMENU_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_RESTOREDSIMENU_1", "");

		// Games/Apps settings
		STR_LANGUAGE = languageini.GetString("LANGUAGE", "LANGUAGE", "");
		STR_CPUSPEED = languageini.GetString("LANGUAGE", "CPUSPEED", "");
		STR_DEBUG = languageini.GetString("LANGUAGE", "DEBUG", "");
		STR_ROMREADLED = languageini.GetString("LANGUAGE", "ROMREADLED", "");
		STR_SNDFREQ = languageini.GetString("LANGUAGE", "SNDFREQ", "");
		STR_RESETSLOT1 = languageini.GetString("LANGUAGE", "RESETSLOT1", "");
		STR_LOADINGSCREEN = languageini.GetString("LANGUAGE", "LOADINGSCREEN", "");
		STR_BOOTSTRAP = languageini.GetString("LANGUAGE", "BOOTSTRAP", "");
		STR_USEGBARUNNER2 = languageini.GetString("LANGUAGE", "USEGBARUNNER2", "");

		STR_SYSTEM = languageini.GetString("LANGUAGE", "SYSTEM", "");
		STR_ON = languageini.GetString("LANGUAGE", "ON", "");
		STR_OFF = languageini.GetString("LANGUAGE", "OFF", "");
		STR_YES = languageini.GetString("LANGUAGE", "YES", "");
		STR_NO = languageini.GetString("LANGUAGE", "NO", "");
		STR_NONE = languageini.GetString("LANGUAGE", "NONE", "");
		STR_POWER = languageini.GetString("LANGUAGE", "POWER", "");
		STR_CAMERA = languageini.GetString("LANGUAGE", "CAMERA", "");
		STR_REGULAR = languageini.GetString("LANGUAGE", "REGULAR", "");
		STR_RELEASE = languageini.GetString("LANGUAGE", "RELEASE", "");
		STR_NIGHTLY = languageini.GetString("LANGUAGE", "NIGHTLY", "");

		STR_DESCRIPTION_LANGUAGE_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_LANGUAGE_1", "");
		STR_DESCRIPTION_LANGUAGE_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_LANGUAGE_2", "");
		STR_DESCRIPTION_LANGUAGE_3 = languageini.GetString("LANGUAGE", "DESCRIPTION_LANGUAGE_3", "");

		STR_DESCRIPTION_CPUSPEED_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_CPUSPEED_1", "");
		STR_DESCRIPTION_CPUSPEED_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_CPUSPEED_2", "");

		STR_DESCRIPTION_DEBUG_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_DEBUG_1", "");
		STR_DESCRIPTION_DEBUG_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_DEBUG_2", "");

		STR_DESCRIPTION_ROMREADLED_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_ROMREADLED_1", "");

		STR_DESCRIPTION_SNDFREQ_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_SNDFREQ_1", "");
		STR_DESCRIPTION_SNDFREQ_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_SNDFREQ_2", "");

		STR_DESCRIPTION_RESETSLOT1_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_RESETSLOT1_1", "");
		STR_DESCRIPTION_RESETSLOT1_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_RESETSLOT1_2", "");

		STR_DESCRIPTION_LOADINGSCREEN_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_LOADINGSCREEN_1", "");
		STR_DESCRIPTION_LOADINGSCREEN_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_LOADINGSCREEN_2", "");

		STR_DESCRIPTION_BOOTSTRAP_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_BOOTSTRAP_1", "");
		STR_DESCRIPTION_BOOTSTRAP_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_BOOTSTRAP_2", "");

		STR_DESCRIPTION_FLASHCARD_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_FLASHCARD_1", "");
		STR_DESCRIPTION_FLASHCARD_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_FLASHCARD_2", "");

		STR_DESCRIPTION_GBARUNNER2_1 = languageini.GetString("LANGUAGE", "DESCRIPTION_GBARUNNER2_1", "");
		STR_DESCRIPTION_GBARUNNER2_2 = languageini.GetString("LANGUAGE", "DESCRIPTION_GBARUNNER2_2", "");

		// Flashcard settings
		STR_FLASHCARD_SELECT = languageini.GetString("LANGUAGE", "FLASHCARD_SELECT", "");
		STR_LEFTRIGHT_FLASHCARD = languageini.GetString("LANGUAGE", "STR_LEFTRIGHT_FLASHCARD", "");
		STR_AB_SETRETURN = languageini.GetString("LANGUAGE", "STR_AB_SETRETURN", "");
	}
}
