name: Import translations from Crowdin

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup environment
        run: git config --global safe.directory '*'

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install python -y

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Crowdin CLI
        run: |
          npm i -g @crowdin/cli

      - name: Pull from Crowdin
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          crowdin pull

      - name: Pull origin
        run: git pull origin master --ff-only # Pull origin in case a commit has been done while updating

      # This makes sure that the app actually builds before pushing to master
      - name: Build test
        run: |
          make package

      - name: Commit changes
        continue-on-error: true
        run: |
          git config user.email "twlbot@flashcarts.net"
          git config user.name "TWLBot"

          git checkout master
          git commit -a -m "Automatic translation import"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.TWLBOT_TOKEN }}
